### ISSUE TITLE
The cake is a lie

### ISSUE THREAD

**Issue by szinter** [rangeoshun/wormer#30] opened 2016-04-01 12:53 UTC
After wall warp, the food is not picked up.
![bug3](https://cloud.githubusercontent.com/assets/295901/14207293/6d633042-f819-11e5-87c7-e072bdd6f3a7.png)

**Comment by rangeoshun** [comment] 2016-04-01 12:59
Through walls they ignore you.

**Comment by szinter** [comment] 2016-04-01 13:05
So it's a feature? :D //NO

**Comment by rangeoshun** [comment] 2016-04-03 16:50
No, I just noted for myself what's going on. Can't replicate tho.. I think this issue was caused by  displacement. The colliding function had the reference of the old position. It should be fixed.

**Closed as completed by rangeoshun** 2016-04-03 16:50 UTC

**Comment by szinter** [comment] 2016-04-04 07:55
:+1:
